acpi_device = "acpi_video0"
xrandr_display = "eDP-1-0"
brightness_increment = 10

[acpi_events]
brightness_up = "video/brightnessup BRTUP 00000086 00000000"
brightness_down = "video/brightnessdown BRTDN 00000087 00000000"
